# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 78286b29dc53d80db693385f3f03838b8ccd44f78fba09560d2d0b125a9c6e23f0d8f6306eaecd0b54959b5e0694891155ca6ca9cbf6040d932f0c841ee4f61b

test:
  secret_key_base: 3af2ff0dc47b67ed6db8d8c0c64caa7c0ac10a7e9b3bd96c86fd4933fdbe1aef9ad78da794eed47e7b71f437d6e3bb77c6c689eb72708c38eb8a51311227a09d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
